/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PostNewRouteImport } from './routes/post.new'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as ForumNewRouteImport } from './routes/forum.new'
import { Route as ForumQuestionIdRouteImport } from './routes/forum.$questionId'
import { Route as CommunitiesSlugRouteImport } from './routes/communities_.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiCloudinaryUploadRouteImport } from './routes/api/cloudinary-upload'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostNewRoute = PostNewRouteImport.update({
  id: '/post/new',
  path: '/post/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumNewRoute = ForumNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ForumRoute,
} as any)
const ForumQuestionIdRoute = ForumQuestionIdRouteImport.update({
  id: '/$questionId',
  path: '/$questionId',
  getParentRoute: () => ForumRoute,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/communities_/$slug',
  path: '/communities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudinaryUploadRoute = ApiCloudinaryUploadRouteImport.update({
  id: '/api/cloudinary-upload',
  path: '/api/cloudinary-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/admin/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/category/$slug': typeof CategorySlugRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/forum/$questionId': typeof ForumQuestionIdRoute
  '/forum/new': typeof ForumNewRoute
  '/post/$postId': typeof PostPostIdRoute
  '/post/new': typeof PostNewRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/category/$slug': typeof CategorySlugRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/forum/$questionId': typeof ForumQuestionIdRoute
  '/forum/new': typeof ForumNewRoute
  '/post/$postId': typeof PostPostIdRoute
  '/post/new': typeof PostNewRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/category/$slug': typeof CategorySlugRoute
  '/communities_/$slug': typeof CommunitiesSlugRoute
  '/forum/$questionId': typeof ForumQuestionIdRoute
  '/forum/new': typeof ForumNewRoute
  '/post/$postId': typeof PostPostIdRoute
  '/post/new': typeof PostNewRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/communities'
    | '/datenschutz'
    | '/events'
    | '/forum'
    | '/login'
    | '/onboarding'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/waitlist'
    | '/admin/waitlist'
    | '/api/cloudinary-upload'
    | '/category/$slug'
    | '/communities/$slug'
    | '/forum/$questionId'
    | '/forum/new'
    | '/post/$postId'
    | '/post/new'
    | '/profile/$username'
    | '/profile/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/communities'
    | '/datenschutz'
    | '/events'
    | '/forum'
    | '/login'
    | '/onboarding'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/waitlist'
    | '/admin/waitlist'
    | '/api/cloudinary-upload'
    | '/category/$slug'
    | '/communities/$slug'
    | '/forum/$questionId'
    | '/forum/new'
    | '/post/$postId'
    | '/post/new'
    | '/profile/$username'
    | '/profile/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/communities'
    | '/datenschutz'
    | '/events'
    | '/forum'
    | '/login'
    | '/onboarding'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/waitlist'
    | '/admin/waitlist'
    | '/api/cloudinary-upload'
    | '/category/$slug'
    | '/communities_/$slug'
    | '/forum/$questionId'
    | '/forum/new'
    | '/post/$postId'
    | '/post/new'
    | '/profile/$username'
    | '/profile/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunitiesRoute: typeof CommunitiesRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EventsRoute: typeof EventsRoute
  ForumRoute: typeof ForumRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WaitlistRoute: typeof WaitlistRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  ApiCloudinaryUploadRoute: typeof ApiCloudinaryUploadRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  PostPostIdRoute: typeof PostPostIdRoute
  PostNewRoute: typeof PostNewRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ProfileEditRoute: typeof ProfileEditRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/new': {
      id: '/post/new'
      path: '/post/new'
      fullPath: '/post/new'
      preLoaderRoute: typeof PostNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/new': {
      id: '/forum/new'
      path: '/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof ForumNewRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum/$questionId': {
      id: '/forum/$questionId'
      path: '/$questionId'
      fullPath: '/forum/$questionId'
      preLoaderRoute: typeof ForumQuestionIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/communities_/$slug': {
      id: '/communities_/$slug'
      path: '/communities/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudinary-upload': {
      id: '/api/cloudinary-upload'
      path: '/api/cloudinary-upload'
      fullPath: '/api/cloudinary-upload'
      preLoaderRoute: typeof ApiCloudinaryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ForumRouteChildren {
  ForumQuestionIdRoute: typeof ForumQuestionIdRoute
  ForumNewRoute: typeof ForumNewRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumQuestionIdRoute: ForumQuestionIdRoute,
  ForumNewRoute: ForumNewRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunitiesRoute: CommunitiesRoute,
  DatenschutzRoute: DatenschutzRoute,
  EventsRoute: EventsRoute,
  ForumRoute: ForumRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WaitlistRoute: WaitlistRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  ApiCloudinaryUploadRoute: ApiCloudinaryUploadRoute,
  CategorySlugRoute: CategorySlugRoute,
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  PostPostIdRoute: PostPostIdRoute,
  PostNewRoute: PostNewRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ProfileEditRoute: ProfileEditRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
